### ISSUE TITLE
Even more faster with `Promise.all`

### ISSUE THREAD

**Issue by micalevisk** [iamrokt/duration-cli#1]
Hi!

you could replace the following 
https://github.com/iamrokt/duration-cli/blob/73127a89f25a553582890abb6bba6cc5ce11eccb/index.js#L66-L80

with something like
![image](https://user-images.githubusercontent.com/13461315/131202255-62c07d39-65df-4179-9a52-33262a6d1fef.png)

to retrieve the durations concurrently instead of sequentially, and so reducing the total time spent.

**Comment by iamrokt** [comment]
Thanks Micael! I made a commit with the changes you proposed.
You are awesome!

**Comment by micalevisk** [comment]
@iamrokt you (or the author) just need to close it

**Comment by iamrokt** [comment]
Thank you my friend!
